### PR TITLE
Distinguish code from text and format OSX setup instructions

### PR DESCRIPTION
**Pull request by CorySpitzer**
Make it prettier and easier to read

### CODE REVIEW

**Comment by CorySpitzer** [comment]
closes #37

**Comment by georgemandis** [comment]
Hey @CorySpitzer — do you want to add the link to XAMPP somewhere in the documentation here, per #37 ? Then I can merge the pull request.

**Comment by CorySpitzer** [comment]
Sure. I will link to their setup instructions in my other PR (not this one from my master branch).

**Comment by CorySpitzer** [comment]
Moved to this PR: https://github.com/ShiftGithub/shiftcal/pull/39

**Pull request closed without merging**
