### PR TITLE
Added JSON feed for events over next 14 days.

### PR DESCRIPTION
**Pull request by georgemandis**
Should be findable at [shift2bikes.org/ca/viewjson.php](http://shift2bikes.org/ca/viewjson.php) when implemented. Spits out JSON data similar to the RSS feed.

### CODE REVIEW

**Comment by fool** [comment]
it's in!  I had to adjust include path to be ../../include/account.php

**Comment by georgemandis** [comment]
Hmm In which file out of curiosity?

**Comment by fool** [comment]
oh!  I read your location request as you wanted it for some reason to be at http://shift2bikes.org/cal/ca/viewjson.php, so I dutifully made a subdirectory and stuck it in.

Undone, because I now realize you just wanted it to be in the cal/ directory.  your code is awesome, my reading comprehension could maybe use some work ;)

**Comment by georgemandis** [comment]
My inability to write without typos did not help the situation :)

Looks great! Thanks. :)

**Pull request merged**
